// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalabatSmartVillage.Models;

#nullable disable

namespace TalabatSmartVillage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TalabatSmartVillage.Auth.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TalabatSmartVillage.Auth.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("postalcode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TalabatSmartVillage.Dtos.LoginViewModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("LoginDto");
                });

            modelBuilder.Entity("TalabatSmartVillage.Dtos.RegisterViewModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("postalCode")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("RegisterDto");
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quick and easy meals",
                            Name = "Fast Food"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cheesy and delicious",
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Japanese delicacy",
                            Name = "Sushi"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Juicy and filling",
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tender and tasty",
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Fresh from the ocean",
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sweet and indulgent",
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Nutritious and balanced",
                            Name = "Healthy"
                        });
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Crispy spicy chicken burger",
                            IsAvailable = true,
                            Name = "Zinger Burger",
                            Price = 85.00m,
                            RestaurantId = 1,
                            image = "https://www.kfc.com.au/images/products/zinger-burger.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "8 pieces crispy chicken bucket",
                            IsAvailable = true,
                            Name = "Bucket Meal",
                            Price = 250.00m,
                            RestaurantId = 1,
                            image = "https://www.kfc.com/images/products/bucket.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh creamy coleslaw side",
                            IsAvailable = true,
                            Name = "Coleslaw",
                            Price = 20.00m,
                            RestaurantId = 1,
                            image = "https://www.seriouseats.com/thmb/coleslaw.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cold refreshing drink",
                            IsAvailable = true,
                            Name = "Pepsi",
                            Price = 15.00m,
                            RestaurantId = 1,
                            image = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Pepsi_can.png/800px-Pepsi_can.png"
                        },
                        new
                        {
                            Id = 5,
                            Description = "6 pieces spicy hot wings",
                            IsAvailable = true,
                            Name = "Hot Wings",
                            Price = 75.00m,
                            RestaurantId = 1,
                            image = "https://www.seriouseats.com/thmb/hot-wings.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Grilled chicken in a flour wrap",
                            IsAvailable = false,
                            Name = "Twister Wrap",
                            Price = 70.00m,
                            RestaurantId = 1,
                            image = "https://www.kfc.com/images/products/twister.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Creamy mashed potato with gravy",
                            IsAvailable = true,
                            Name = "Mashed Potato",
                            Price = 25.00m,
                            RestaurantId = 1,
                            image = "https://www.seriouseats.com/thmb/mashed-potato.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Rich moist chocolate slice",
                            IsAvailable = true,
                            Name = "Chocolate Cake",
                            Price = 35.00m,
                            RestaurantId = 1,
                            image = "https://www.seriouseats.com/thmb/chocolate-cake.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Description = "12 pieces with 2 sides and drinks",
                            IsAvailable = true,
                            Name = "Family Meal",
                            Price = 450.00m,
                            RestaurantId = 1,
                            image = "https://www.kfc.com/images/products/family-meal.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Grilled sweet corn side",
                            IsAvailable = true,
                            Name = "Corn on the Cob",
                            Price = 18.00m,
                            RestaurantId = 1,
                            image = "https://www.seriouseats.com/thmb/corn-cob.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Classic double beef burger",
                            IsAvailable = true,
                            Name = "Big Mac",
                            Price = 95.00m,
                            RestaurantId = 2,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Golden crispy french fries",
                            IsAvailable = true,
                            Name = "McFries",
                            Price = 30.00m,
                            RestaurantId = 2,
                            image = "https://www.seriouseats.com/thmb/french-fries.jpg"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Vanilla ice cream with Oreo",
                            IsAvailable = true,
                            Name = "McFlurry Oreo",
                            Price = 45.00m,
                            RestaurantId = 2,
                            image = "https://www.seriouseats.com/thmb/mcflurry.jpg"
                        },
                        new
                        {
                            Id = 14,
                            Description = "10 pieces crispy nuggets",
                            IsAvailable = true,
                            Name = "Chicken McNuggets",
                            Price = 80.00m,
                            RestaurantId = 2,
                            image = "https://www.seriouseats.com/thmb/nuggets.jpg"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Quarter pound beef patty burger",
                            IsAvailable = true,
                            Name = "Quarter Pounder",
                            Price = 105.00m,
                            RestaurantId = 2,
                            image = "https://www.seriouseats.com/thmb/quarter-pounder.jpg"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Warm baked apple pie",
                            IsAvailable = true,
                            Name = "Apple Pie",
                            Price = 20.00m,
                            RestaurantId = 2,
                            image = "https://www.seriouseats.com/thmb/apple-pie.jpg"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Crispy fish fillet burger",
                            IsAvailable = false,
                            Name = "Filet-O-Fish",
                            Price = 75.00m,
                            RestaurantId = 2,
                            image = "https://www.seriouseats.com/thmb/filet-o-fish.jpg"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Thick creamy chocolate milkshake",
                            IsAvailable = true,
                            Name = "Chocolate Shake",
                            Price = 40.00m,
                            RestaurantId = 2,
                            image = "https://www.seriouseats.com/thmb/chocolate-shake.jpg"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Kids meal with toy",
                            IsAvailable = true,
                            Name = "Happy Meal",
                            Price = 65.00m,
                            RestaurantId = 2,
                            image = "https://www.seriouseats.com/thmb/happy-meal.jpg"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Double beef with double cheese",
                            IsAvailable = true,
                            Name = "Double Cheeseburger",
                            Price = 85.00m,
                            RestaurantId = 2,
                            image = "https://www.seriouseats.com/thmb/double-cheeseburger.jpg"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Classic tomato and mozzarella",
                            IsAvailable = true,
                            Name = "Margherita",
                            Price = 120.00m,
                            RestaurantId = 3,
                            image = "https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Loaded spicy pepperoni pizza",
                            IsAvailable = true,
                            Name = "Pepperoni",
                            Price = 145.00m,
                            RestaurantId = 3,
                            image = "https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg"
                        },
                        new
                        {
                            Id = 23,
                            Description = "BBQ sauce with grilled chicken",
                            IsAvailable = true,
                            Name = "BBQ Chicken",
                            Price = 155.00m,
                            RestaurantId = 3,
                            image = "https://www.seriouseats.com/thmb/bbq-chicken-pizza.jpg"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Toasted garlic butter bread",
                            IsAvailable = true,
                            Name = "Garlic Bread",
                            Price = 35.00m,
                            RestaurantId = 3,
                            image = "https://www.seriouseats.com/thmb/garlic-bread.jpg"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Spicy tomato pasta",
                            IsAvailable = true,
                            Name = "Pasta Arrabiata",
                            Price = 90.00m,
                            RestaurantId = 3,
                            image = "https://www.seriouseats.com/thmb/pasta-arrabiata.jpg"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Pizza with cheese stuffed crust",
                            IsAvailable = false,
                            Name = "Cheesy Bites",
                            Price = 165.00m,
                            RestaurantId = 3,
                            image = "https://www.seriouseats.com/thmb/cheesy-bites.jpg"
                        },
                        new
                        {
                            Id = 27,
                            Description = "8 pieces BBQ chicken wings",
                            IsAvailable = true,
                            Name = "Chicken Wings",
                            Price = 95.00m,
                            RestaurantId = 3,
                            image = "https://www.seriouseats.com/thmb/chicken-wings.jpg"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Romaine lettuce with caesar dressing",
                            IsAvailable = true,
                            Name = "Caesar Salad",
                            Price = 65.00m,
                            RestaurantId = 3,
                            image = "https://www.seriouseats.com/thmb/caesar-salad.jpg"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Warm chocolate lava cake",
                            IsAvailable = true,
                            Name = "Lava Cake",
                            Price = 55.00m,
                            RestaurantId = 3,
                            image = "https://www.seriouseats.com/thmb/lava-cake.jpg"
                        },
                        new
                        {
                            Id = 30,
                            Description = "330ml cold pepsi can",
                            IsAvailable = true,
                            Name = "Pepsi Can",
                            Price = 15.00m,
                            RestaurantId = 3,
                            image = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Pepsi_can.png/800px-Pepsi_can.png"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Loaded with all toppings",
                            IsAvailable = true,
                            Name = "ExtravaganZZa",
                            Price = 175.00m,
                            RestaurantId = 4,
                            image = "https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Triple meat loaded pizza",
                            IsAvailable = true,
                            Name = "MeatZZa",
                            Price = 165.00m,
                            RestaurantId = 4,
                            image = "https://www.seriouseats.com/thmb/meatzza.jpg"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Fresh garden vegetables pizza",
                            IsAvailable = true,
                            Name = "Veggie Feast",
                            Price = 130.00m,
                            RestaurantId = 4,
                            image = "https://www.seriouseats.com/thmb/veggie-pizza.jpg"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Cheese filled crust pizza",
                            IsAvailable = false,
                            Name = "Stuffed Crust",
                            Price = 155.00m,
                            RestaurantId = 4,
                            image = "https://www.seriouseats.com/thmb/stuffed-crust.jpg"
                        },
                        new
                        {
                            Id = 35,
                            Description = "10 pieces crispy chicken bites",
                            IsAvailable = true,
                            Name = "Chicken Kickers",
                            Price = 85.00m,
                            RestaurantId = 4,
                            image = "https://www.seriouseats.com/thmb/chicken-kickers.jpg"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Crispy seasoned potato wedges",
                            IsAvailable = true,
                            Name = "Potato Wedges",
                            Price = 40.00m,
                            RestaurantId = 4,
                            image = "https://www.seriouseats.com/thmb/potato-wedges.jpg"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Warm chocolate brownie",
                            IsAvailable = true,
                            Name = "Brownie",
                            Price = 45.00m,
                            RestaurantId = 4,
                            image = "https://www.seriouseats.com/thmb/brownie.jpg"
                        },
                        new
                        {
                            Id = 38,
                            Description = "330ml cold diet pepsi",
                            IsAvailable = true,
                            Name = "Diet Pepsi",
                            Price = 15.00m,
                            RestaurantId = 4,
                            image = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Pepsi_can.png/800px-Pepsi_can.png"
                        },
                        new
                        {
                            Id = 39,
                            Description = "4 dipping sauces of your choice",
                            IsAvailable = true,
                            Name = "Dips Pack",
                            Price = 20.00m,
                            RestaurantId = 4,
                            image = "https://www.seriouseats.com/thmb/dips.jpg"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Garlic bread with melted cheese",
                            IsAvailable = true,
                            Name = "Cheesy Garlic Bread",
                            Price = 45.00m,
                            RestaurantId = 4,
                            image = "https://www.seriouseats.com/thmb/cheesy-garlic-bread.jpg"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Fresh salmon with avocado",
                            IsAvailable = false,
                            Name = "Salmon Roll",
                            Price = 150.00m,
                            RestaurantId = 5,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 42,
                            Description = "8 slices fresh tuna sashimi",
                            IsAvailable = false,
                            Name = "Tuna Sashimi",
                            Price = 180.00m,
                            RestaurantId = 5,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Shrimp tempura topped with avocado",
                            IsAvailable = false,
                            Name = "Dragon Roll",
                            Price = 165.00m,
                            RestaurantId = 5,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Traditional Japanese miso soup",
                            IsAvailable = false,
                            Name = "Miso Soup",
                            Price = 35.00m,
                            RestaurantId = 5,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Steamed salted soybeans",
                            IsAvailable = false,
                            Name = "Edamame",
                            Price = 40.00m,
                            RestaurantId = 5,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Crab, cucumber and avocado",
                            IsAvailable = false,
                            Name = "California Roll",
                            Price = 120.00m,
                            RestaurantId = 5,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Crispy deep fried prawns",
                            IsAvailable = false,
                            Name = "Prawn Tempura",
                            Price = 145.00m,
                            RestaurantId = 5,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Pan fried Japanese dumplings",
                            IsAvailable = false,
                            Name = "Gyoza",
                            Price = 85.00m,
                            RestaurantId = 5,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Matcha flavored ice cream",
                            IsAvailable = false,
                            Name = "Green Tea Ice Cream",
                            Price = 55.00m,
                            RestaurantId = 5,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Rich pork broth noodle soup",
                            IsAvailable = false,
                            Name = "Ramen",
                            Price = 130.00m,
                            RestaurantId = 5,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 51,
                            Description = "8 pieces colorful sushi roll",
                            IsAvailable = true,
                            Name = "Rainbow Roll",
                            Price = 160.00m,
                            RestaurantId = 6,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Tuna with spicy mayo sauce",
                            IsAvailable = true,
                            Name = "Spicy Tuna Roll",
                            Price = 145.00m,
                            RestaurantId = 6,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Grilled chicken in teriyaki sauce",
                            IsAvailable = true,
                            Name = "Chicken Teriyaki",
                            Price = 140.00m,
                            RestaurantId = 6,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Crispy shrimp in sushi roll",
                            IsAvailable = true,
                            Name = "Shrimp Tempura Roll",
                            Price = 155.00m,
                            RestaurantId = 6,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Japanese rice cake with ice cream",
                            IsAvailable = true,
                            Name = "Mochi Ice Cream",
                            Price = 65.00m,
                            RestaurantId = 6,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Grilled chicken skewers",
                            IsAvailable = true,
                            Name = "Yakitori",
                            Price = 95.00m,
                            RestaurantId = 6,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Japanese octopus balls",
                            IsAvailable = false,
                            Name = "Takoyaki",
                            Price = 80.00m,
                            RestaurantId = 6,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Thick wheat noodles in broth",
                            IsAvailable = true,
                            Name = "Udon Noodles",
                            Price = 110.00m,
                            RestaurantId = 6,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Hot Japanese green tea latte",
                            IsAvailable = true,
                            Name = "Matcha Latte",
                            Price = 45.00m,
                            RestaurantId = 6,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 60,
                            Description = "6 slices fresh salmon sashimi",
                            IsAvailable = true,
                            Name = "Salmon Sashimi",
                            Price = 170.00m,
                            RestaurantId = 6,
                            image = "https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Cheeseburger with ShackSauce",
                            IsAvailable = true,
                            Name = "ShackBurger",
                            Price = 130.00m,
                            RestaurantId = 7,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Bacon cheeseburger with cherry peppers",
                            IsAvailable = true,
                            Name = "SmokeShack",
                            Price = 150.00m,
                            RestaurantId = 7,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Cheeseburger with crispy mushroom",
                            IsAvailable = true,
                            Name = "Shack Stack",
                            Price = 170.00m,
                            RestaurantId = 7,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Classic crinkle cut fries",
                            IsAvailable = true,
                            Name = "Crinkle Cut Fries",
                            Price = 45.00m,
                            RestaurantId = 7,
                            image = "https://www.seriouseats.com/thmb/french-fries.jpg"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Hand spun vanilla milkshake",
                            IsAvailable = true,
                            Name = "Vanilla Shake",
                            Price = 75.00m,
                            RestaurantId = 7,
                            image = "https://www.seriouseats.com/thmb/vanilla-shake.jpg"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Hand spun strawberry milkshake",
                            IsAvailable = true,
                            Name = "Strawberry Shake",
                            Price = 75.00m,
                            RestaurantId = 7,
                            image = "https://www.seriouseats.com/thmb/strawberry-shake.jpg"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Crispy chicken sandwich",
                            IsAvailable = true,
                            Name = "Chicken Shack",
                            Price = 120.00m,
                            RestaurantId = 7,
                            image = "https://www.seriouseats.com/thmb/chicken-sandwich.jpg"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Crinkle fries with cheese sauce",
                            IsAvailable = false,
                            Name = "Cheese Fries",
                            Price = 60.00m,
                            RestaurantId = 7,
                            image = "https://www.seriouseats.com/thmb/cheese-fries.jpg"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Crispy portobello mushroom burger",
                            IsAvailable = true,
                            Name = "Portobello Burger",
                            Price = 125.00m,
                            RestaurantId = 7,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Fresh squeezed lemonade",
                            IsAvailable = true,
                            Name = "Lemonade",
                            Price = 35.00m,
                            RestaurantId = 7,
                            image = "https://www.seriouseats.com/thmb/lemonade.jpg"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Two beef patties all the way",
                            IsAvailable = true,
                            Name = "Five Guys Burger",
                            Price = 155.00m,
                            RestaurantId = 8,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Single beef patty burger",
                            IsAvailable = true,
                            Name = "Little Burger",
                            Price = 120.00m,
                            RestaurantId = 8,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Seasoned fries with cajun spice",
                            IsAvailable = true,
                            Name = "Cajun Fries",
                            Price = 50.00m,
                            RestaurantId = 8,
                            image = "https://www.seriouseats.com/thmb/cajun-fries.jpg"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Beef patty with crispy bacon",
                            IsAvailable = true,
                            Name = "Bacon Burger",
                            Price = 165.00m,
                            RestaurantId = 8,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Choose from 10 mix-in flavors",
                            IsAvailable = true,
                            Name = "Milkshake",
                            Price = 80.00m,
                            RestaurantId = 8,
                            image = "https://www.seriouseats.com/thmb/milkshake.jpg"
                        },
                        new
                        {
                            Id = 76,
                            Description = "All beef kosher hot dog",
                            IsAvailable = false,
                            Name = "Hot Dog",
                            Price = 90.00m,
                            RestaurantId = 8,
                            image = "https://www.seriouseats.com/thmb/hot-dog.jpg"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Toasted bread with melted cheese",
                            IsAvailable = true,
                            Name = "Grilled Cheese",
                            Price = 70.00m,
                            RestaurantId = 8,
                            image = "https://www.seriouseats.com/thmb/grilled-cheese.jpg"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Bacon lettuce and tomato sandwich",
                            IsAvailable = true,
                            Name = "BLT Sandwich",
                            Price = 95.00m,
                            RestaurantId = 8,
                            image = "https://www.seriouseats.com/thmb/blt-sandwich.jpg"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Grilled vegetables in a bun",
                            IsAvailable = true,
                            Name = "Veggie Sandwich",
                            Price = 85.00m,
                            RestaurantId = 8,
                            image = "https://www.seriouseats.com/thmb/veggie-sandwich.jpg"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Free refill soft drink",
                            IsAvailable = true,
                            Name = "Fountain Drink",
                            Price = 20.00m,
                            RestaurantId = 8,
                            image = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Pepsi_can.png/800px-Pepsi_can.png"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Half pound Angus beef burger",
                            IsAvailable = true,
                            Name = "Thickburger",
                            Price = 135.00m,
                            RestaurantId = 9,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Crispy fried chicken sandwich",
                            IsAvailable = true,
                            Name = "Chicken Fillet",
                            Price = 95.00m,
                            RestaurantId = 9,
                            image = "https://www.seriouseats.com/thmb/chicken-sandwich.jpg"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Hand scooped natural cut fries",
                            IsAvailable = true,
                            Name = "Natural Cut Fries",
                            Price = 35.00m,
                            RestaurantId = 9,
                            image = "https://www.seriouseats.com/thmb/french-fries.jpg"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Fries with cheese and bacon",
                            IsAvailable = true,
                            Name = "Loaded Fries",
                            Price = 55.00m,
                            RestaurantId = 9,
                            image = "https://www.seriouseats.com/thmb/loaded-fries.jpg"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Beef patty with mushroom sauce",
                            IsAvailable = false,
                            Name = "Mushroom Burger",
                            Price = 125.00m,
                            RestaurantId = 9,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 86,
                            Description = "Crispy battered onion rings",
                            IsAvailable = true,
                            Name = "Onion Rings",
                            Price = 30.00m,
                            RestaurantId = 9,
                            image = "https://www.seriouseats.com/thmb/onion-rings.jpg"
                        },
                        new
                        {
                            Id = 87,
                            Description = "Eggs bacon and cheese in a wrap",
                            IsAvailable = true,
                            Name = "Breakfast Burrito",
                            Price = 75.00m,
                            RestaurantId = 9,
                            image = "https://www.seriouseats.com/thmb/breakfast-burrito.jpg"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Fresh peach milkshake",
                            IsAvailable = true,
                            Name = "Peach Shake",
                            Price = 55.00m,
                            RestaurantId = 9,
                            image = "https://www.seriouseats.com/thmb/peach-shake.jpg"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Double half pound Angus burger",
                            IsAvailable = true,
                            Name = "Double Thickburger",
                            Price = 185.00m,
                            RestaurantId = 9,
                            image = "https://images.themodernproper.com/production/posts/2016/ClassicCheeseBurger_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1749310239&s=463b18fc3bb51dc5d96e866c848527c4"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Classic creamy coleslaw",
                            IsAvailable = true,
                            Name = "Cole Slaw",
                            Price = 20.00m,
                            RestaurantId = 9,
                            image = "https://www.seriouseats.com/thmb/coleslaw.jpg"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Crispy buttermilk chicken",
                            IsAvailable = false,
                            Name = "Chicken Sandwich",
                            Price = 110.00m,
                            RestaurantId = 10,
                            image = "https://www.seriouseats.com/thmb/chicken-sandwich.jpg"
                        },
                        new
                        {
                            Id = 92,
                            Description = "3 pieces spicy or mild chicken",
                            IsAvailable = false,
                            Name = "3 Piece Chicken",
                            Price = 125.00m,
                            RestaurantId = 10,
                            image = "https://www.seriouseats.com/thmb/fried-chicken.jpg"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Classic Louisiana red beans rice",
                            IsAvailable = false,
                            Name = "Red Beans Rice",
                            Price = 40.00m,
                            RestaurantId = 10,
                            image = "https://www.seriouseats.com/thmb/red-beans-rice.jpg"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Buttermilk flaky biscuit",
                            IsAvailable = false,
                            Name = "Biscuit",
                            Price = 15.00m,
                            RestaurantId = 10,
                            image = "https://www.seriouseats.com/thmb/biscuit.jpg"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Creamy macaroni and cheese",
                            IsAvailable = false,
                            Name = "Mac and Cheese",
                            Price = 45.00m,
                            RestaurantId = 10,
                            image = "https://www.seriouseats.com/thmb/mac-cheese.jpg"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Creamy mashed potatoes with gravy",
                            IsAvailable = false,
                            Name = "Mashed Potatoes",
                            Price = 30.00m,
                            RestaurantId = 10,
                            image = "https://www.seriouseats.com/thmb/mashed-potato.jpg"
                        },
                        new
                        {
                            Id = 97,
                            Description = "5 pieces chicken tenders",
                            IsAvailable = false,
                            Name = "Chicken Tenders",
                            Price = 100.00m,
                            RestaurantId = 10,
                            image = "https://www.seriouseats.com/thmb/chicken-tenders.jpg"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Seasoned Cajun spiced fries",
                            IsAvailable = false,
                            Name = "Cajun Fries",
                            Price = 35.00m,
                            RestaurantId = 10,
                            image = "https://www.seriouseats.com/thmb/cajun-fries.jpg"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Fresh strawberry lemonade",
                            IsAvailable = false,
                            Name = "Strawberry Lemonade",
                            Price = 40.00m,
                            RestaurantId = 10,
                            image = "https://www.seriouseats.com/thmb/lemonade.jpg"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Extra spicy chicken tenders",
                            IsAvailable = false,
                            Name = "Spicy Tenders",
                            Price = 110.00m,
                            RestaurantId = 10,
                            image = "https://www.seriouseats.com/thmb/spicy-tenders.jpg"
                        });
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalOrderPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("restaurant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Nasr City",
                            CategoryId = 1,
                            IsOpen = true,
                            Name = "KFC"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza, Mohandessin",
                            CategoryId = 1,
                            IsOpen = true,
                            Name = "McDonalds"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria, Smouha",
                            CategoryId = 2,
                            IsOpen = true,
                            Name = "Pizza Hut"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cairo, Maadi",
                            CategoryId = 2,
                            IsOpen = true,
                            Name = "Dominos"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Cairo, Zamalek",
                            CategoryId = 3,
                            IsOpen = false,
                            Name = "Sushi King"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Giza, Sheikh Zayed",
                            CategoryId = 3,
                            IsOpen = true,
                            Name = "Tokyo House"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Cairo, New Cairo",
                            CategoryId = 4,
                            IsOpen = true,
                            Name = "Shake Shack"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Cairo, Heliopolis",
                            CategoryId = 4,
                            IsOpen = true,
                            Name = "Five Guys"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Giza, Dokki",
                            CategoryId = 5,
                            IsOpen = true,
                            Name = "Hardees"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Cairo, Nasr City",
                            CategoryId = 5,
                            IsOpen = false,
                            Name = "Popeyes"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Alexandria, Corniche",
                            CategoryId = 6,
                            IsOpen = true,
                            Name = "Fish Market"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Cairo, Maadi",
                            CategoryId = 6,
                            IsOpen = true,
                            Name = "Sea Breeze"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Cairo, City Stars",
                            CategoryId = 7,
                            IsOpen = true,
                            Name = "Cinnabon"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Giza, Mohandessin",
                            CategoryId = 7,
                            IsOpen = true,
                            Name = "Baskin Robbins"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Cairo, New Cairo",
                            CategoryId = 8,
                            IsOpen = true,
                            Name = "Salad Bar"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("TalabatSmartVillage.Auth.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TalabatSmartVillage.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TalabatSmartVillage.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("TalabatSmartVillage.Auth.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalabatSmartVillage.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TalabatSmartVillage.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.MenuItem", b =>
                {
                    b.HasOne("TalabatSmartVillage.Models.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.Order", b =>
                {
                    b.HasOne("TalabatSmartVillage.Models.Restaurant", "Restaurant")
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalabatSmartVillage.Auth.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.OrderItem", b =>
                {
                    b.HasOne("TalabatSmartVillage.Models.MenuItem", "menuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalabatSmartVillage.Models.Order", "order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("menuItem");

                    b.Navigation("order");
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.Restaurant", b =>
                {
                    b.HasOne("TalabatSmartVillage.Models.Category", "Category")
                        .WithMany("Restaurants")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TalabatSmartVillage.Auth.AppUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.Category", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TalabatSmartVillage.Models.Restaurant", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
